spring:
  application:
    name: echo

  datasource:
    url: jdbc:postgresql://localhost:5432/echo
    username: postgres
    password: jay123


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true